### ISSUE TITLE
Kubernetes for CKA - part 2

### ISSUE THREAD

**Issue by sreekanth-sree** [djkormo/katacoda-scenarios#1]
Hi 

first up all thanks to creating scenerios like this.It will be really helpful to person like me for preparing CKA exam certification
in the CKA Second part 2 even though i am done with the exercises  it is still showing complete the task 
please find attached image

![image1](https://user-images.githubusercontent.com/43569989/101615564-48431b80-3a34-11eb-939b-e24d63e362db.png)

**Comment by djkormo** [comment]
Be my first tester.

https://github.com/djkormo/katacoda-scenarios/blob/master/kubernetes-cka-part2/step2-verify.sh

Check if the all statements are completed

**Comment by sreekanth-sree** [comment]
Hi
I have gone through this already getting the output "done"

what my confusion in your answers section in as a  Bonus  asking to check the values from the pg_tables 
 

> select * from pg_tables



![image](https://user-images.githubusercontent.com/43569989/101623591-ac6add00-3a3e-11eb-9009-61c63c7c702e.png)

**Comment by djkormo** [comment]
I've just corrected the https://github.com/djkormo/katacoda-scenarios/blob/master/kubernetes-cka-part2/answers-all.md

**Comment by djkormo** [comment]
Closing
